name: Deploy to hjellum.net

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version: [7.4, 8.0, 8.1, 8.2]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: pdo, pdo_mysql, mbstring
        coverage: none
    
    - name: Validate composer.json and composer.lock
      run: composer validate --strict
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: Run PHP syntax check
      run: |
        find . -name "*.php" -not -path "./vendor/*" -exec php -l {} \;
    
    - name: Test database connection class
      run: |
        php -r "
        require_once 'config/database.production.php';
        \$db = new Database();
        echo 'Database class loaded successfully\n';
        "

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to hjellum.net
      run: |
        echo "🚀 Deployment would happen here"
        echo "📁 Files ready for upload:"
        find . -type f -name "*.php" -o -name "*.html" -o -name "*.css" -o -name "*.js" | head -10
        echo ""
        echo "📝 Next steps:"
        echo "1. Upload files to /oppskrifter/ on hjellum.net"
        echo "2. Configure database credentials"
        echo "3. Import database schema"
        echo "4. Test the application"